### ISSUE TITLE
How to determine from which array to fetch data for upload?

### ISSUE THREAD

**Issue by nookery** [apple/sample-cloudkit-sync-engine#12]
Assuming that two sets of data are stored locally 
- contacts
- orders

both of which are kept in sync with CloudKit.
How to determine from which array to fetch data for upload at `nextRecordZoneChangeBatch `?

```swift
func nextRecordZoneChangeBatch(_ context: CKSyncEngine.SendChangesContext, syncEngine: CKSyncEngine) async -> CKSyncEngine.RecordZoneChangeBatch? {
        
        Logger.database.info("Returning next record change batch for context: \(context)")
        
        let scope = context.options.scope
        let changes = syncEngine.state.pendingRecordZoneChanges.filter { scope.contains($0) }
        let contacts = self.appData.contacts
        
        let batch = await CKSyncEngine.RecordZoneChangeBatch(pendingChanges: changes) { recordID in
            
// ====== How to determine from which array to fetch data for upload? Contacts or orders? ======

            if let contact = contacts[recordID.recordName] {
                let record = contact.lastKnownRecord ?? CKRecord(recordType: Contact.recordType, recordID: recordID)
                contact.populateRecord(record)
                return record
            } else {
                // We might have pending changes that no longer exist in our database. We can remove those from the state.
                syncEngine.state.remove(pendingRecordZoneChanges: [ .saveRecord(recordID) ])
                return nil
            }
        }
        return batch
    }
```

**Comment by malhal** [comment]
As a quick fix you could just search both arrays.

**Comment by nookery** [comment]
> As a quick fix you could just search both arrays.

Yes, I have ultimately decided to proceed this way. Thanks.

**Comment by jmjauer** [comment]
I have the exact same issue. I haven't tried it yet, but I think a lookup over persisted CKRecord encodeSystemFields should work. Since you need to persist the system fields anyway, there is no extra work to do. The only difference would be that you would have to persist the system fields before telling CKSyncEngine what to do.

**Comment by timimahoney** [comment]
Another way to solve this is to treat all your CloudKit-related objects in terms of a single type/protocol. For example, instead of "orders" and "contacts", write your code in terms of "cloud objects". That way, you can use the same identifier space for all of them, and you could just look up the "cloud object" by record name.

You could potentially do this by conforming `Contact` and `Order` to a common `CloudObject` protocol. Or you could have a separate `CloudObject` object that contains a `contact` or an `order` (maybe in an enum?).

Alternatively, you could keep a separate index/dictionary of record name -> type, then use that to determine which place to look.

Not saying these are all great options, but they might be possibilities.

**Comment by nookery** [comment]
Suppose there are 1,000 tables stored in the database(I use SwiftData), and each table contains some records, such as:

- orders
- contacts
- users
- groups
- products
- ...

Most importantly, each record has a uuid attribute.

Now, the Sync Engine says: Find the record with uuid xxxx. 

### Solution-1

Query from all the 1,000 tables, which may take a long time.

### Solution-2

- Create another table, which records what type a certain uuid is, such as: 

```
1234 - Order
4567 - User 
9876 - Product
``` 

In this way, the target table can be quickly found from 1,000 tables, then the record can be quickly found from the target table.

Compared with the first way, it saves time, but adds additional code and storage space. 

Since the number of tables is not large, and each table contains not much data either, I finally chose the simplest first solution.

**Comment by jmjauer** [comment]
@nookery 

### Solution-3

Simply use your persistent CKRecord cache to look up the type information. There is no need for another table as you have already saved this information.

**Comment by nookery** [comment]
> @nookery
> 
> ### Solution-3
> Simply use your persistent CKRecord cache to look up the type information. There is no need for another table as you have already saved this information.

I searched for "encodeSystemFields" throughout the project and got the following code:
```swift
/// A deserialized version of `lastKnownRecordData`.
/// Will return `nil` if there is no data or if the deserialization fails for some reason.
var lastKnownRecord: CKRecord? {
    
    get {
        if let data = self.lastKnownRecordData {
            do {
                let unarchiver = try NSKeyedUnarchiver(forReadingFrom: data)
                unarchiver.requiresSecureCoding = true
                return CKRecord(coder: unarchiver)
            } catch {
                // Why would this happen? What could go wrong? 🔥
                Logger.dataModel.fault("Failed to decode local system fields record: \(error)")
                return nil
            }
        } else {
            return nil
        }
    }
    
    set {
        if let newValue {
            let archiver = NSKeyedArchiver(requiringSecureCoding: true)
            newValue.encodeSystemFields(with: archiver)
            self.lastKnownRecordData = archiver.encodedData
        } else {
            self.lastKnownRecordData = nil
        }
    }
}
```
Perhaps your idea can be described like below:

There is a table to store CKRecord cache:

| uuid | type| lastKnownRecordData |
|-----|-----|-----|
| 123 | Order | xxx |
| 456 | User | xxx |
| 789 | Contact | xxx |

Every time the latest record is obtained from iCloud, insert(or update) a piece of data here.  

Now, the Sync Engine says: Find the record with uuid xxxx. Then I can quickly know the type corresponding to this uuid.

**Comment by jmjauer** [comment]
It is even simpler:

To make synchronization efficient, you need to persist the CKRecord you get from the server - this is the piece of code in the sample application:

```
let archiver = NSKeyedArchiver(requiringSecureCoding: true)
newValue.encodeSystemFields(with: archiver)
self.lastKnownRecordData = archiver.encodedData
```

So whenever you need the type information for a CKRecord.ID, you simply load the persisted CKRecord and read the type from it:

```
let unarchiver = try NSKeyedUnarchiver(forReadingFrom: data)
unarchiver.requiresSecureCoding = true
let recordType = CKRecord(coder: unarchiver).recordType
```

One change you probably need to make is to persist a `CKRecord` *before* you first commit changes to the server via `CKSyncEngine` - after that, you just update your local `CKRecord` cache whenever `CKSyncEngine` tells you to. This is all you need (and you need it anyways, since you need the change token, wich is encoded in lastKnownRecordData):

uuid | lastKnownRecordData
-- | --
123  | xxx
456 | xxx
789 | xxx

**Comment by nookery** [comment]
> It is even simpler:
> 
> To make synchronization efficient, you need to persist the CKRecord you get from the server - this is the piece of code in the sample application:
> 
> ```
> let archiver = NSKeyedArchiver(requiringSecureCoding: true)
> newValue.encodeSystemFields(with: archiver)
> self.lastKnownRecordData = archiver.encodedData
> ```
> 
> So whenever you need the type information for a CKRecord.ID, you simply load the persisted CKRecord and read the type from it:
> 
> ```
> let unarchiver = try NSKeyedUnarchiver(forReadingFrom: data)
> unarchiver.requiresSecureCoding = true
> let recordType = CKRecord(coder: unarchiver).recordType
> ```
> 
> One change you probably need to make is to persist a `CKRecord` _before_ you first commit changes to the server via `CKSyncEngine` - after that, you just update your local `CKRecord` cache whenever `CKSyncEngine` tells you to. This is all you need (and you need it anyways, since you need the change token, wich is encoded in lastKnownRecordData):
> 
> uuid	lastKnownRecordData
> 123	xxx
> 456	xxx
> 789	xxx

Many thanks. That a cool idea!
